# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - frontend/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Check current directory structure for debugging
- script: |
    pwd
    ls -la
  displayName: 'Check working directory'

- script: |
    npm ci
  workingDirectory: $(Build.SourcesDirectory)/frontend
  displayName: 'npm install'

- script: |
    chmod +x node_modules/.bin/react-scripts
    npm run build
  workingDirectory: $(Build.SourcesDirectory)/frontend
  displayName: 'npm build'

# Check build output directory
- script: |
    ls -la
    ls -la build || echo "Build directory not found"
  workingDirectory: $(Build.SourcesDirectory)/frontend
  displayName: 'Check build output'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/frontend/build'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build files'
  continueOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'frontend-build'
  displayName: 'Publish artifacts'
  continueOnError: true
